# -*- coding: utf-8 -*-
"""Logo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12WlE9Pe1ZLwU-ppM7HvOCZ6Ua6rjc5Kf
"""



def detect_logos(path):
    """Detects logos in the file."""
    import os 
    os.environ['GOOGLE_APPLICATION_CREDENTIALS']="C:/Users/Alex/Downloads/qwiklabs-gcp-02-bc8c0d449ccd-93af816f7568.json"
    from google.cloud import vision
    import io
    client = vision.ImageAnnotatorClient()

    with io.open(path, 'rb') as image_file:
        content = image_file.read()

    image = vision.Image(content=content)

    response = client.logo_detection(image=image)
    logos = response.logo_annotations
    print('Logos:')
    
    logo_list=[]

    for logo in logos:
        logo_list.append(logo.description)

    if response.error.message:
        raise Exception(
            '{}\nFor more info on error messages, check: '
            'https://cloud.google.com/apis/design/errors'.format(
                response.error.message))
     
    return logo_list
    
if __name__=='__main__':
    path='H:/SEM 3/cloud lab/LANDMARK PROJECT/moscow.png'
    res=detect_landmarks(path)
    print(res)

#!pip install google-cloud-vision